### ISSUE TITLE
legal issues

### ISSUE THREAD

**Issue by LickTheCheese** [icanotc/icanotc.github.io#1]
i did not leave a review on your site.

please remove it cuz thats illegak

**Comment by icanotc** [comment]
no owen it's not u 
so many people have that name
and no one acc get on to the website

**Comment by LickTheCheese** [comment]
yes, it is obviously me, but it it "is not me", than that would still be a fake review

**Comment by icanotc** [comment]
yea but did i say thats real? the whole website is fake u dummy thicc

**Comment by LickTheCheese** [comment]
then please do not claim the content of your website is true.

**Comment by icanotc** [comment]
the content on my website is NOT true

**Comment by LickTheCheese** [comment]
in the actual website, not a random issue that will probably be closed and nobody will easily find would probably be a better place

**Comment by icanotc** [comment]
wym

**Comment by LickTheCheese** [comment]
people will assume the content of your site is true and they wont look through random issues to find out that its actually fake

**Comment by icanotc** [comment]
yea thats the whole point of the site

its a joke

**Comment by LickTheCheese** [comment]
why have you done this vincent

**Comment by icanotc** [comment]
yes

**Comment by LickTheCheese** [comment]
Duplicate of #1

**Comment by icanotc** [comment]
true
